name: egm722myproject
channels:
  - conda-forge
  - defaults
dependencies:

  - python=3.9
  - geopandas
  - cartopy>=0.21
  - jupyterlab
  - ipywidgets
  - rasterio
  - pyepsg
  - folium
  - notebook=6.2.0
  - rasterstats=0.14.0
  - ipympl>0.9

